apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml
  - apps-of-apps-git-sync.yaml
  - cert-manager-git-sync.yaml
  - gateway_cillium-git-sync.yaml
  - demo-pod-info.yaml
