apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway-public.yaml
  - gateway-privee.yaml
  - services-nodeport.yaml

namespace: networking

secretGenerator:
  - name: default-public-cert
    options:
      disableNameSuffixHash: true
    namespace: networking
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: default-private-cert
    options:
      disableNameSuffixHash: true
    namespace: networking
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key
